export { default as Manage } from './manage'
export { default as SingleProductView } from './SingleProductView'
export { default as newProduct } from './newProductForm'
export { default as editProduct } from './editProductForm'
export { default as ReviewForm } from './ReviewForm'
// export { default as Review } from './Review'
